#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
# sudo pip install fysom
#
from fysom import Fysom
import wiringpi2 as wiringpi
#import lib.fakelib as wiringpi
import pcd8544.lcd as lcd
#import lib.fakelib as lcd
from lib.daemon import Daemon
from lib.configuration import Configuration
import os, sys, signal

if not os.geteuid() == 0:
    sys.exit('Script must be run as root')

# Define constants
INPUT, OUTPUT = LOW, HIGH = OFF, ON = [0, 1]
UP, DOWN, RIGHT,LEFT,ENTER = BUTTONS = [8,9,10,11,12]
PIN_BASE = 65
I2C_ADDR = 0x20
PUD_UP = 2

class RpiMonitorLCD(Daemon):

  def initialize(self):

    # Initialize wiringpi
    wiringpi.wiringPiSetup()
    wiringpi.mcp23017Setup(PIN_BASE,I2C_ADDR)
    for button in BUTTONS:
      wiringpi.pinMode(PIN_BASE + button,INPUT)
      wiringpi.pullUpDnControl(PIN_BASE + button,PUD_UP)

    # Get configuration from file
    self.configuration = Configuration()
    self.configuration.load('/home/pi/RPi-Monitor-LCD/rpimonitorlcd.conf')

    self.modules = map(__import__,self.configuration.data['modules'])

    # Initialize state machine
    initial = self.configuration.data['fsm']['initial']
    fsm = Fysom({'initial': {'state': initial, 'event': 'init', 'defer': True},
                 'events':  self.configuration.data['fsm']['events'],
                 'callbacks': {
                     'onup':    self.onup,
                     'ondown':  self.ondown,
                     'onleft':  self.onleft,
                     'onright': self.onright,
                     'onenter': self.onenter }})
    fsm.onchangestate = self.onchangestate 
    self.ACTIONS = [ fsm.up, fsm.down, fsm.left, fsm.right, fsm.enter ]

    # Initialize LCD
    lcd.init()
    self.lighttimer = 0
    fsm.init()
    #for command in configuration.data['pages'][initial]['content']:
    #  eval(command)
    #self.seconds = 5
    #self.lightOn()
    signal.signal(signal.SIGTERM, self.exiting)
 
  #
  def lightOn(self):
    self.lighttimer = self.seconds * 50
    lcd.backlight(ON)

  # Catch SIGTERM to turn off the screen when the daemon is stopped
  def exiting(self, signum, frame):
    lcd.cls()
    lcd.backlight(OFF)
    sys.exit(0)


  # Implement callbacks
  def onchangestate(self,e):
    for command in self.configuration.data['pages'][e.dst]['content']:
      eval(command)
    self.seconds = 5
    self.lightOn()

  def onup(self,msg):
    lcd.cls()
    self.lightOn()
    eval(configuration.data[fsm.current]['onup'])
    lcd.center_text(3,'key up')

  def ondown(self,msg):
    lcd.cls()
    self.lightOn() 
    eval(configuration.data[fsm.current]['ondown'])
    lcd.center_text(3,'key down')

  def onleft(self,msg):
    lcd.cls()
    self.lightOn()
    eval(configuration.data[fsm.current]['onleft'])
    lcd.center_text(3,'key left')

  def onright(self,msg):
    lcd.cls()
    self.lightOn()
    eval(configuration.data[fsm.current]['onright'])
    lcd.center_text(3,'key right')

  def onenter(self,msg):
    lcd.cls()
    self.lightOn()
    lcd.center_text(3,'key enter')


  def run(self):
    self.initialize()
    # Start main loop
    while True:
      for index,button in enumerate(BUTTONS):
        button_state = wiringpi.digitalRead(button)
        if button_state:
          try:
            self.ACTIONS[index];
          finally:
            pass
      if self.lighttimer > 0:
        self.lighttimer -= 1
        if self.lighttimer == 0:
          lcd.backlight(OFF)
      wiringpi.delay(20)


if __name__ == "__main__":
  if len(sys.argv) == 2:
    daemon = RpiMonitorLCD('/var/run/rpimonitorlcd.pid','/dev/stdin','/dev/stdout','/dev/stderr')
    #daemon = RpiMonitorLCD('/var/run/rpimonitorlcd.pid')
    if 'start' == sys.argv[1]:
      daemon.start()
    elif 'stop' == sys.argv[1]:
      daemon.stop()
    elif 'restart' == sys.argv[1]:
      daemon.restart()
    else:
      print "Unknown command"
      sys.exit(2)
    sys.exit(0)
  else:
    print "usage: %s start|stop|restart" % sys.argv[0]
    sys.exit(2)
